from django.urls import path, include # Make sure include is imported
from rest_framework.routers import DefaultRouter # Import DefaultRouter
from .views import TaskViewSet 

router = DefaultRouter()
router.register(r'tasks', TaskViewSet, basename='task') # Register our ViewSet

urlpatterns = [
    path('', include(router.urls)), # Include all URLs generated by the router
]