from django.urls import path, include # Make sure include is imported
from rest_framework.routers import DefaultRouter 
from .views import TaskViewSet 
from django.http import HttpResponse 
router = DefaultRouter()
router.register(r'tasks', TaskViewSet, basename='task') # Register our ViewSet

urlpatterns = [
    path('', lambda request: HttpResponse("API is running"), name='root'),
    path('', include(router.urls)), # Include all URLs generated by the router
    path('api/register/', RegisterView.as_view(), name='register'),
]