# Generated by Django 5.2.4 on 2026-02-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('priorit', models.CharField(blank=True, choices=[('L', 'Low'), ('M', 'Middle'), ('H', 'High')], help_text='Task Priority (Low, Medium, High)', max_length=1, null=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
