# Generated by Django 5.2.4 on 2026-02-20 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='priorit',
            new_name='priority',
        ),
    ]
